#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install haproxy=2.0.\*

sudo sed -i "$ a \\\nfrontend flanders\n\tmode http\n\tbind *:80\n\tdefault_backend flanders-backend" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a \\\nbackend flanders-backend\n\tmode http\n\tbalance roundrobin\n\tserver 118920-web-01 100.25.154.128:80 check\n\tserver 118920-web-02 54.158.197.36:80 check" /etc/haproxy/haproxy.cfg

sudo +x /etc/init.d/haproxy
sudo service haproxy restart
